# Generated by Django 2.2.3 on 2019-07-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190709_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='href',
            field=models.CharField(default='def', max_length=80),
        ),
    ]
