# Generated by Django 2.2.3 on 2019-07-09 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_category_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='href',
        ),
    ]
